from typing import Any, Protocol, Sequence

import pandas as pd


class AnalyticsRepository(Protocol):
    def table_exists(self, table: str) -> bool: ...

    def query_df(self, sql: str, params: Sequence[Any] | None = None) -> pd.DataFrame: ...

    def register_table(self, name: str, df: pd.DataFrame) -> None: ...

    def count_municipios(self) -> int: ...


class ReportStore(Protocol):
    def save_report(self, df: pd.DataFrame, nome_arquivo: str) -> None: ...

    def load_report(self, nome_arquivo: str) -> pd.DataFrame | None: ...


class AIService(Protocol):
    def search_relevant(self, pergunta: str, n_results: int = 5) -> str: ...

    def complete(self, system_prompt: str, historico: list[dict], pergunta: str, contexto: str) -> tuple[str, int]: ...
