from __future__ import annotations

from semantic_layer.models import SemanticDimension, SemanticEntity, SemanticMetric, SemanticRegistry

ENTITIES: tuple[SemanticEntity, ...] = (
    SemanticEntity(
        entity_id="candidato",
        name="Candidato",
        description="Ator politico analisado pela plataforma em nivel agregado.",
        primary_key=["candidate_id"],
        canonical_table="gold_candidate_context",
        dimensions=["candidate_id", "nome_politico", "partido", "cargo"],
        related_entities=["base_eleitoral", "recomendacao", "gasto"],
    ),
    SemanticEntity(
        entity_id="territorio",
        name="Territorio",
        description="Unidade territorial agregada para ranking, score e alocacao.",
        primary_key=["territorio_id"],
        canonical_table="gold_territory_profile",
        dimensions=["territorio_id", "uf", "municipio_nome", "zona"],
        related_entities=["municipio", "secao_eleitoral", "cluster_territorial"],
    ),
    SemanticEntity(
        entity_id="secao_eleitoral",
        name="Secao eleitoral",
        description="Menor unidade eleitoral agregada usada no master index.",
        primary_key=["ano_eleicao", "uf", "cod_municipio_tse", "zona", "secao"],
        canonical_table="gold_territorial_electoral_master_index",
        dimensions=["secao", "zona", "local_votacao"],
        related_entities=["territorio", "local_votacao"],
    ),
    SemanticEntity(
        entity_id="local_votacao",
        name="Local de votacao",
        description="Local fisico agregado que concentra secoes eleitorais.",
        primary_key=["ano_eleicao", "uf", "cod_municipio_tse", "zona", "local_votacao"],
        canonical_table="gold_territorial_electoral_master_index",
        dimensions=["local_votacao", "zona", "municipio_nome"],
        related_entities=["secao_eleitoral", "territorio"],
    ),
    SemanticEntity(
        entity_id="municipio",
        name="Municipio",
        description="Municipio harmonizado entre codigos TSE e IBGE.",
        primary_key=["uf", "cod_municipio_tse", "cod_municipio_ibge"],
        canonical_table="gold_territory_profile",
        dimensions=["uf", "cod_municipio_tse", "cod_municipio_ibge", "municipio_nome"],
        related_entities=["territorio"],
    ),
    SemanticEntity(
        entity_id="cluster_territorial",
        name="Cluster territorial",
        description="Agrupamento operacional de territorios para leitura executiva.",
        primary_key=["territorial_cluster_id"],
        canonical_table="gold_territorial_clusters",
        dimensions=["territorial_cluster_id", "cluster_label"],
        related_entities=["territorio"],
    ),
    SemanticEntity(
        entity_id="tema",
        name="Tema",
        description="Tema publico agregado usado para afinidade territorial e narrativa.",
        primary_key=["territorio_id", "tema"],
        canonical_table="gold_thematic_affinity",
        dimensions=["tema", "territorio_id"],
        related_entities=["territorio", "candidato"],
    ),
    SemanticEntity(
        entity_id="recomendacao",
        name="Recomendacao",
        description="Recomendacao agregada de acao e recurso para territorio/candidato/cenario.",
        primary_key=["scenario_id", "candidate_id", "territorio_id"],
        canonical_table="gold_allocation_recommendations",
        dimensions=["scenario_id", "candidate_id", "territorio_id", "tipo_acao_sugerida"],
        related_entities=["candidato", "territorio", "cenario"],
    ),
    SemanticEntity(
        entity_id="cenario",
        name="Cenario",
        description="Configuracao de simulacao de alocacao.",
        primary_key=["scenario_id"],
        canonical_table="gold_allocation_recommendations",
        dimensions=["scenario_id"],
        related_entities=["recomendacao"],
    ),
    SemanticEntity(
        entity_id="gasto",
        name="Gasto",
        description="Resumo financeiro agregado de campanha e eficiencia.",
        primary_key=["candidate_id"],
        canonical_table="gold_campaign_finance_efficiency",
        dimensions=["candidate_id"],
        related_entities=["candidato"],
    ),
    SemanticEntity(
        entity_id="base_eleitoral",
        name="Base eleitoral",
        description="Forca eleitoral observada ou estimada por candidato e territorio.",
        primary_key=["candidate_id", "territorio_id"],
        canonical_table="gold_electoral_base_strength",
        dimensions=["candidate_id", "territorio_id"],
        related_entities=["candidato", "territorio"],
    ),
    SemanticEntity(
        entity_id="concorrencia",
        name="Concorrencia",
        description="Paisagem competitiva agregada por territorio.",
        primary_key=["territorio_id"],
        canonical_table="gold_competition_landscape",
        dimensions=["territorio_id", "leader_candidate_id"],
        related_entities=["territorio", "candidato"],
    ),
)


METRICS: tuple[SemanticMetric, ...] = (
    SemanticMetric(
        metric_id="forca_base",
        name="Forca de base",
        description="Forca eleitoral do candidato no territorio.",
        formula="base_strength_score",
        grain="candidate_id + territorio_id",
        source_table="gold_electoral_base_strength",
        source_columns=["base_strength_score"],
        value_type="score",
        consumers=["scoring", "ranking", "dashboard"],
        quality_notes="Depende da cobertura de resultados por secao e da qualidade do master index.",
    ),
    SemanticMetric(
        metric_id="potencial_expansao",
        name="Potencial de expansao",
        description="Potencial de crescimento em territorios nao consolidados.",
        formula="potencial_expansao_score",
        grain="candidate_id + territorio_id",
        source_table="gold_priority_score",
        source_columns=["potencial_expansao_score"],
        value_type="score",
        consumers=["scoring", "simulador"],
    ),
    SemanticMetric(
        metric_id="intensidade_competitiva",
        name="Intensidade competitiva",
        description="Nivel agregado de competicao local.",
        formula="competition_score",
        grain="territorio_id",
        source_table="gold_competition_landscape",
        source_columns=["competition_score"],
        value_type="score",
        consumers=["scoring", "relatorios"],
    ),
    SemanticMetric(
        metric_id="aderencia_tematica",
        name="Aderencia tematica",
        description="Aderencia entre temas e territorio.",
        formula="AVG(thematic_affinity_score)",
        grain="territorio_id",
        source_table="gold_thematic_affinity",
        source_columns=["thematic_affinity_score"],
        value_type="score",
        consumers=["mensagem", "copiloto"],
    ),
    SemanticMetric(
        metric_id="eficiencia_gasto",
        name="Eficiencia de gasto",
        description="Eficiencia financeira relativa do candidato.",
        formula="finance_efficiency_score",
        grain="candidate_id",
        source_table="gold_campaign_finance_efficiency",
        source_columns=["finance_efficiency_score"],
        value_type="score",
        consumers=["simulador", "allocation"],
    ),
    SemanticMetric(
        metric_id="prioridade_territorial",
        name="Prioridade territorial",
        description="Score final de priorizacao territorial.",
        formula="score_prioridade_final",
        grain="candidate_id + territorio_id",
        source_table="gold_priority_score",
        source_columns=["score_prioridade_final"],
        value_type="score",
        consumers=["ranking", "allocation", "dashboard"],
    ),
    SemanticMetric(
        metric_id="confianca_recomendacao",
        name="Confianca da recomendacao",
        description="Confianca operacional da recomendacao, baseada em qualidade e score.",
        formula="COALESCE(confidence_score, score_prioridade_final * data_quality_score)",
        grain="scenario_id + candidate_id + territorio_id",
        source_table="gold_allocation_recommendations",
        source_columns=["score_prioridade_final", "percentual_orcamento_sugerido"],
        value_type="score",
        consumers=["copiloto", "relatorios"],
        quality_notes="Quando confidence_score nao existir, usar proxy derivado com cautela.",
    ),
    SemanticMetric(
        metric_id="cobertura_territorial",
        name="Cobertura territorial",
        description="Cobertura de fontes e confiabilidade territorial.",
        formula="data_quality_score",
        grain="territorio_id",
        source_table="gold_territory_profile",
        source_columns=["data_quality_score"],
        value_type="score",
        consumers=["data quality", "dashboard"],
    ),
    SemanticMetric(
        metric_id="custo_por_voto_estimado",
        name="Custo por voto estimado",
        description="Despesa total dividida por votos observados do candidato.",
        formula="custo_por_voto_estimado",
        grain="candidate_id",
        source_table="gold_campaign_finance_efficiency",
        source_columns=["custo_por_voto_estimado"],
        value_type="money",
        consumers=["simulador", "relatorios"],
        quality_notes="Nao deve ser interpretado como custo por secao sem evidencia territorial.",
    ),
    SemanticMetric(
        metric_id="share_potencial",
        name="Share potencial",
        description="Share eleitoral observado ou proxy de potencial relativo.",
        formula="historical_vote_share",
        grain="candidate_id + territorio_id",
        source_table="territorial_recommendation_features",
        source_columns=["historical_vote_share"],
        value_type="ratio",
        consumers=["feature store", "scoring"],
    ),
)


DIMENSIONS: tuple[SemanticDimension, ...] = (
    SemanticDimension(
        dimension_id="candidate_id",
        name="ID do candidato",
        description="Identificador canonico do candidato.",
        entity_id="candidato",
        source_table="gold_candidate_context",
        source_column="candidate_id",
    ),
    SemanticDimension(
        dimension_id="territorio_id",
        name="ID do territorio",
        description="Identificador canonico de territorio agregado.",
        entity_id="territorio",
        source_table="gold_territory_profile",
        source_column="territorio_id",
    ),
    SemanticDimension(
        dimension_id="municipio_nome",
        name="Municipio",
        description="Nome harmonizado do municipio.",
        entity_id="municipio",
        source_table="gold_territory_profile",
        source_column="municipio_nome",
    ),
    SemanticDimension(
        dimension_id="zona",
        name="Zona eleitoral",
        description="Zona eleitoral padronizada.",
        entity_id="territorio",
        source_table="gold_territory_profile",
        source_column="zona",
    ),
    SemanticDimension(
        dimension_id="tema",
        name="Tema",
        description="Tema publico agregado.",
        entity_id="tema",
        source_table="gold_thematic_affinity",
        source_column="tema",
    ),
    SemanticDimension(
        dimension_id="scenario_id",
        name="Cenario",
        description="Identificador do cenario de alocacao.",
        entity_id="cenario",
        source_table="gold_allocation_recommendations",
        source_column="scenario_id",
    ),
)


def build_semantic_registry() -> SemanticRegistry:
    return SemanticRegistry(entities=list(ENTITIES), metrics=list(METRICS), dimensions=list(DIMENSIONS))


def metric_by_id(metric_id: str) -> SemanticMetric | None:
    return build_semantic_registry().metric(metric_id)


def entity_by_id(entity_id: str) -> SemanticEntity | None:
    return build_semantic_registry().entity(entity_id)
