apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-canary
  namespace: intel-eleitoral
spec:
  replicas: 4
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: { duration: 2m }
        - setWeight: 30
        - pause: { duration: 5m }
        - setWeight: 60
        - pause: { duration: 5m }
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/acarloshenrique/inteligencia-eleitoral-sp2026-api:latest
          ports:
            - containerPort: 8000
