from __future__ import annotations

from collections.abc import Iterable
from typing import Literal

from data_catalog.models import (
    BusinessMetadata,
    Coverage,
    DatasetDependency,
    EnterpriseDataCatalog,
    EnterpriseDataset,
    PrioritizationRow,
    ProductCapability,
    QualityRule,
    TechnicalMetadata,
)


def _coverage(start: str, end: str, notes: str = "") -> Coverage:
    return Coverage(start=start, end=end, notes=notes)


def _technical(
    dataset_id: str,
    layer: str,
    partitioning: list[str],
    lineage_upstream: list[str] | None = None,
    lineage_downstream: list[str] | None = None,
    incremental_key: str | None = None,
) -> TechnicalMetadata:
    return TechnicalMetadata(
        owner_logico="data-platform",
        schema_uri=f"data_catalog/schemas/{dataset_id}.json",
        storage_path=f"lake/{layer}/{dataset_id}",
        particionamento=partitioning,
        incremental_key=incremental_key,
        lineage_upstream=lineage_upstream or [],
        lineage_downstream=lineage_downstream or [],
    )


def _business(
    finalidade: str,
    capabilities: list[ProductCapability],
    questions: list[str],
    gaps: list[str] | None = None,
    doc: str = "",
) -> BusinessMetadata:
    return BusinessMetadata(
        finalidade_produto=finalidade,
        funcionalidades_suportadas=capabilities,
        perguntas_respondidas=questions,
        lacunas_conhecidas=gaps or [],
        documentacao_negocio=doc,
    )


def _rules(primary_key: list[str], freshness_threshold: float = 1.0) -> list[QualityRule]:
    return [
        QualityRule(
            rule_id="schema_required_columns",
            description="All required analytical columns must be present before promotion.",
            severity="critical",
            check_type="schema",
            target_columns=primary_key,
        ),
        QualityRule(
            rule_id="primary_key_uniqueness",
            description="Primary key must be unique inside the declared coverage and partition.",
            severity="high",
            check_type="uniqueness",
            target_columns=primary_key,
            threshold=0.995,
        ),
        QualityRule(
            rule_id="freshness_within_expected_period",
            description="Dataset must be refreshed according to its declared periodicity or marked stale.",
            severity="medium",
            check_type="freshness",
            threshold=freshness_threshold,
        ),
    ]


def _dep(
    dataset_id: str,
    dependency_type: str,
    join_keys: list[str],
    confidence: float,
    notes: str = "",
) -> DatasetDependency:
    return DatasetDependency(
        dataset_id=dataset_id,
        dependency_type=dependency_type,  # type: ignore[arg-type]
        join_keys=join_keys,
        join_confidence=confidence,
        notes=notes,
    )


ENTERPRISE_DATASETS: tuple[EnterpriseDataset, ...] = (
    EnterpriseDataset(
        dataset_id="tse_boletim_urna_secao_bronze",
        nome="Boletim de urna por secao",
        descricao="Arquivo bruto do boletim de urna com votos por secao eleitoral, urna e cargo.",
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/dataset/boletim-de-urna",
        formato="zip/csv",
        camada_alvo="bronze",
        granularidade="secao",
        periodicidade="eleitoral",
        chave_primaria=["ANO_ELEICAO", "TURNO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "CARGO"],
        chaves_estrangeiras_possiveis=["COD_MUN_TSE", "ZONA", "SECAO", "SQ_CANDIDATO"],
        cobertura_temporal=_coverage("2008", "latest", "Coverage depends on TSE open-data availability by election."),
        cobertura_geografica=_coverage("BR", "BR", "National; SP is the primary product scope."),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=100,
        status_ingestao="ingested",
        estrategia_atualizacao="Download by election year and UF; preserve original zip hash in bronze manifest.",
        observacoes_join="Exact join by ANO_ELEICAO, SIGLA_UF, COD_MUN_TSE, ZONA and SECAO after TSE code normalization.",
        score_confiabilidade=0.97,
        tier=1,
        technical_metadata=_technical(
            "tse_boletim_urna_secao_bronze",
            "bronze",
            ["ANO_ELEICAO", "SIGLA_UF"],
            lineage_downstream=["tse_resultados_eleitorais_secao_silver"],
        ),
        business_metadata=_business(
            "Foundation for electoral strength and section-level territorial precision.",
            ["forca_eleitoral", "competicao"],
            ["Where did the candidate perform by section?", "Which sections show competitive pressure?"],
            doc="Critical source for electoral base strength.",
        ),
        quality_rules=_rules(["ANO_ELEICAO", "TURNO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "CARGO"]),
        product_capabilities=["forca_eleitoral", "competicao"],
        lineage_notes="Raw evidence retained before any aggregation.",
    ),
    EnterpriseDataset(
        dataset_id="tse_resultados_eleitorais_secao_silver",
        nome="Resultados eleitorais por secao",
        descricao="Resultados limpos e harmonizados por candidato, cargo, municipio, zona e secao.",
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="secao",
        periodicidade="eleitoral",
        chave_primaria=["ANO_ELEICAO", "TURNO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "SQ_CANDIDATO"],
        chaves_estrangeiras_possiveis=["SQ_CANDIDATO", "COD_MUN_TSE", "COD_MUN_IBGE", "ZONA", "SECAO"],
        cobertura_temporal=_coverage("2008", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=99,
        status_ingestao="ingested",
        estrategia_atualizacao="Reprocess idempotently from bronze when TSE releases corrected files.",
        observacoes_join="Requires crosswalk for COD_MUN_TSE to COD_MUN_IBGE when enriching with IBGE sources.",
        score_confiabilidade=0.95,
        tier=1,
        technical_metadata=_technical(
            "tse_resultados_eleitorais_secao_silver",
            "silver",
            ["ANO_ELEICAO", "SIGLA_UF"],
            lineage_upstream=["tse_boletim_urna_secao_bronze"],
            lineage_downstream=["gold_fact_territorio_eleitoral", "gold_metricas_prioridade_territorial"],
        ),
        business_metadata=_business(
            "Canonical source for candidate performance, ranking and competitive analysis.",
            ["forca_eleitoral", "competicao", "contexto_candidato"],
            ["What is the candidate base by section?", "Where is expansion plausible?"],
            doc="Input for base strength, retention and competition scores.",
        ),
        quality_rules=_rules(["ANO_ELEICAO", "TURNO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "SQ_CANDIDATO"]),
        dependencies=[
            _dep(
                "tse_boletim_urna_secao_bronze",
                "source",
                ["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO"],
                1.0,
            )
        ],
        product_capabilities=["forca_eleitoral", "competicao", "contexto_candidato"],
    ),
    EnterpriseDataset(
        dataset_id="tse_perfil_eleitorado_secao_silver",
        nome="Perfil do eleitorado por secao",
        descricao="Perfil agregado de eleitorado por secao com faixa etaria, genero e escolaridade.",
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="secao",
        periodicidade="eleitoral",
        chave_primaria=["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "PERFIL_DIMENSAO"],
        chaves_estrangeiras_possiveis=["COD_MUN_TSE", "ZONA", "SECAO"],
        cobertura_temporal=_coverage("2014", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=96,
        status_ingestao="available",
        estrategia_atualizacao="Refresh every election cycle and validate only aggregated demographic buckets.",
        observacoes_join="Exact by TSE territorial keys; never join to individual voter records.",
        score_confiabilidade=0.92,
        tier=1,
        technical_metadata=_technical(
            "tse_perfil_eleitorado_secao_silver",
            "silver",
            ["ANO_ELEICAO", "SIGLA_UF"],
            lineage_downstream=["gold_fact_territorio_eleitoral"],
        ),
        business_metadata=_business(
            "Adds aggregated electorate context without individual microtargeting.",
            ["tematica_territorial", "capacidade_operacional", "forca_eleitoral"],
            ["Which sections have relevant aggregate demographic context?", "Where should messages be localized?"],
            doc="Allowed only as aggregated territorial signal.",
        ),
        quality_rules=_rules(["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "PERFIL_DIMENSAO"]),
        product_capabilities=["tematica_territorial", "capacidade_operacional", "forca_eleitoral"],
    ),
    EnterpriseDataset(
        dataset_id="tse_eleitorado_local_votacao_silver",
        nome="Eleitorado por local de votacao",
        descricao="Locais de votacao, secoes associadas, endereco e eleitorado agregado.",
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="secao",
        periodicidade="eleitoral",
        chave_primaria=["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "LOCAL_VOTACAO"],
        chaves_estrangeiras_possiveis=["COD_MUN_TSE", "COD_MUN_IBGE", "ZONA", "SECAO", "CD_SETOR"],
        cobertura_temporal=_coverage("2016", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=95,
        status_ingestao="ingested",
        estrategia_atualizacao="Refresh by election year; preserve geocoding confidence as a data quality metric.",
        observacoes_join="Exact on TSE keys; approximate geospatial join to census sectors must retain confidence flag.",
        score_confiabilidade=0.9,
        tier=1,
        technical_metadata=_technical(
            "tse_eleitorado_local_votacao_silver",
            "silver",
            ["ANO_ELEICAO", "SIGLA_UF"],
            lineage_downstream=["gold_fact_territorio_eleitoral"],
        ),
        business_metadata=_business(
            "Supports operational planning by physical voting place and section cluster.",
            ["capacidade_operacional", "forca_eleitoral"],
            ["Where are the high-impact voting places?", "What local operation is feasible by zone?"],
            doc="Core for field operations and logistics.",
        ),
        quality_rules=_rules(["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "LOCAL_VOTACAO"]),
        product_capabilities=["capacidade_operacional", "forca_eleitoral"],
    ),
    EnterpriseDataset(
        dataset_id="tse_cadastro_candidatos_silver",
        nome="Cadastro de candidatos",
        descricao="Candidate registration attributes needed for CandidateProfile and election context.",
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="candidato",
        periodicidade="eleitoral",
        chave_primaria=["ANO_ELEICAO", "SQ_CANDIDATO", "SG_UF", "CD_CARGO"],
        chaves_estrangeiras_possiveis=["SQ_CANDIDATO", "NR_CPF_CANDIDATO_MASKED", "COD_MUN_IBGE"],
        cobertura_temporal=_coverage("2008", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_personal",
        prioridade_produto=93,
        status_ingestao="available",
        estrategia_atualizacao="Refresh every election cycle; expose only fields needed for candidate context.",
        observacoes_join="Exact by SQ_CANDIDATO; personal fields must be minimized and masked in logs.",
        score_confiabilidade=0.93,
        tier=1,
        technical_metadata=_technical(
            "tse_cadastro_candidatos_silver",
            "silver",
            ["ANO_ELEICAO", "SG_UF"],
            lineage_downstream=["gold_candidate_context"],
        ),
        business_metadata=_business(
            "Initial structured profile for candidate context and eligibility filters.",
            ["contexto_candidato"],
            ["Who is the candidate?", "Which race, party and territorial origin define the context?"],
            doc="Seed for Candidate Context Engine.",
        ),
        quality_rules=_rules(["ANO_ELEICAO", "SQ_CANDIDATO", "SG_UF", "CD_CARGO"]),
        product_capabilities=["contexto_candidato"],
    ),
    EnterpriseDataset(
        dataset_id="tse_prestacao_contas_candidato_silver",
        nome="Prestacao de contas por candidato",
        descricao="Campaign revenue and expenses aggregated by candidate and declared geography where available.",
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="candidato",
        periodicidade="eleitoral",
        chave_primaria=["ANO_ELEICAO", "SQ_CANDIDATO", "TIPO_MOVIMENTO", "ID_DOCUMENTO"],
        chaves_estrangeiras_possiveis=["SQ_CANDIDATO", "COD_MUN_IBGE", "COD_MUN_TSE"],
        cobertura_temporal=_coverage("2012", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_personal",
        prioridade_produto=90,
        status_ingestao="available",
        estrategia_atualizacao="Refresh during and after campaign reporting windows; reconcile corrected filings.",
        observacoes_join="Territorial attribution is partial because many expenses are not declared at section/zone level.",
        score_confiabilidade=0.84,
        tier=1,
        technical_metadata=_technical(
            "tse_prestacao_contas_candidato_silver",
            "silver",
            ["ANO_ELEICAO", "SG_UF"],
            lineage_downstream=["gold_metricas_prioridade_territorial"],
        ),
        business_metadata=_business(
            "Supports spend efficiency and estimated cost-per-vote analysis.",
            ["eficiencia_gasto", "contexto_candidato"],
            ["How expensive was the campaign performance?", "Where are spend signals weak or missing?"],
            gaps=["Many expenses lack reliable municipal or zone attribution."],
            doc="Use as aggregate efficiency signal, not deterministic local spend.",
        ),
        quality_rules=_rules(["ANO_ELEICAO", "SQ_CANDIDATO", "TIPO_MOVIMENTO", "ID_DOCUMENTO"]),
        product_capabilities=["eficiencia_gasto", "contexto_candidato"],
        lacunas=["Territorial allocation of expenses may require modeling assumptions."],
    ),
    EnterpriseDataset(
        dataset_id="ibge_malha_setores_censitarios_bronze",
        nome="Malha de setores censitarios",
        descricao="Raw geospatial census-sector boundaries for territorial joins and spatial enrichment.",
        fonte="IBGE",
        url="https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais.html",
        formato="shp/geopackage",
        camada_alvo="bronze",
        granularidade="setor_censitario",
        periodicidade="decenal",
        chave_primaria=["CD_SETOR", "COD_MUN_IBGE"],
        chaves_estrangeiras_possiveis=["COD_MUN_IBGE", "CD_SETOR"],
        cobertura_temporal=_coverage("2010", "2022"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=88,
        status_ingestao="not_started",
        estrategia_atualizacao="Version by census year; retain original geometry and checksum.",
        observacoes_join="Municipality joins are exact; voting-place to sector joins are geospatial and must be flagged.",
        score_confiabilidade=0.91,
        tier=1,
        technical_metadata=_technical(
            "ibge_malha_setores_censitarios_bronze",
            "bronze",
            ["ANO_CENSO", "UF"],
            lineage_downstream=["ibge_censo_2022_agregados_setor_silver", "gold_fact_territorio_eleitoral"],
        ),
        business_metadata=_business(
            "Enables high-granularity territorial context around voting places.",
            ["tematica_territorial", "capacidade_operacional"],
            [
                "Which census sectors surround priority voting places?",
                "Where do territorial constraints affect operations?",
            ],
            doc="Spatial backbone for census enrichment.",
        ),
        quality_rules=_rules(["CD_SETOR", "COD_MUN_IBGE"]),
        product_capabilities=["tematica_territorial", "capacidade_operacional"],
    ),
    EnterpriseDataset(
        dataset_id="ibge_censo_2022_agregados_setor_silver",
        nome="Agregados censitarios do Censo 2022",
        descricao="Aggregated census indicators by sector for income, households, age and education proxies.",
        fonte="IBGE/SIDRA",
        url="https://sidra.ibge.gov.br/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="setor_censitario",
        periodicidade="decenal",
        chave_primaria=["ANO_CENSO", "CD_SETOR", "INDICADOR"],
        chaves_estrangeiras_possiveis=["CD_SETOR", "COD_MUN_IBGE"],
        cobertura_temporal=_coverage("2022", "2022"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=87,
        status_ingestao="not_started",
        estrategia_atualizacao="Snapshot by census release; normalize indicators into controlled thematic dictionary.",
        observacoes_join="Exact by CD_SETOR when sector is available; otherwise aggregate to municipality.",
        score_confiabilidade=0.88,
        tier=1,
        technical_metadata=_technical(
            "ibge_censo_2022_agregados_setor_silver",
            "silver",
            ["ANO_CENSO", "UF"],
            lineage_upstream=["ibge_malha_setores_censitarios_bronze"],
            lineage_downstream=["gold_fact_territorio_eleitoral"],
        ),
        business_metadata=_business(
            "Creates territorial theme signals and socioeconomic context for recommendations.",
            ["tematica_territorial", "capacidade_operacional", "competicao"],
            ["Which themes are territorially relevant?", "Where does socioeconomic context support a message?"],
            doc="Use only aggregated census metrics.",
        ),
        quality_rules=_rules(["ANO_CENSO", "CD_SETOR", "INDICADOR"]),
        dependencies=[_dep("ibge_malha_setores_censitarios_bronze", "source", ["CD_SETOR"], 1.0)],
        product_capabilities=["tematica_territorial", "capacidade_operacional", "competicao"],
    ),
    EnterpriseDataset(
        dataset_id="inep_censo_escolar_municipio_silver",
        nome="Censo Escolar por municipio",
        descricao="Education infrastructure and enrollment indicators aggregated by municipality.",
        fonte="INEP",
        url="https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/censo-escolar",
        formato="parquet",
        camada_alvo="silver",
        granularidade="municipio",
        periodicidade="anual",
        chave_primaria=["ANO", "COD_MUN_IBGE"],
        chaves_estrangeiras_possiveis=["COD_MUN_IBGE", "COD_MUN_TSE"],
        cobertura_temporal=_coverage("2007", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=74,
        status_ingestao="not_started",
        estrategia_atualizacao="Annual ingestion with municipal aggregation and indicator dictionary.",
        observacoes_join="Join to electoral data through TSE-IBGE municipal crosswalk.",
        score_confiabilidade=0.86,
        tier=2,
        technical_metadata=_technical("inep_censo_escolar_municipio_silver", "silver", ["ANO", "UF"]),
        business_metadata=_business(
            "Supports education theme prioritization and local operational context.",
            ["tematica_territorial", "capacidade_operacional"],
            ["Where is education a strong territorial theme?"],
        ),
        quality_rules=_rules(["ANO", "COD_MUN_IBGE"]),
        product_capabilities=["tematica_territorial", "capacidade_operacional"],
    ),
    EnterpriseDataset(
        dataset_id="datasus_cnes_municipio_silver",
        nome="CNES por municipio",
        descricao="Health facilities and capacity indicators aggregated by municipality.",
        fonte="DATASUS/CNES",
        url="https://datasus.saude.gov.br/transferencia-de-arquivos/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="municipio",
        periodicidade="mensal",
        chave_primaria=["ANO", "MES", "COD_MUN_IBGE"],
        chaves_estrangeiras_possiveis=["COD_MUN_IBGE", "COD_MUN_TSE"],
        cobertura_temporal=_coverage("2005", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=72,
        status_ingestao="not_started",
        estrategia_atualizacao="Monthly incremental load by UF and year/month.",
        observacoes_join="Join through COD_MUN_IBGE after municipal crosswalk.",
        score_confiabilidade=0.84,
        tier=2,
        technical_metadata=_technical(
            "datasus_cnes_municipio_silver", "silver", ["ANO", "MES", "UF"], incremental_key="ANO_MES"
        ),
        business_metadata=_business(
            "Supports health theme and public-service capacity context.",
            ["tematica_territorial", "capacidade_operacional"],
            ["Where is health infrastructure a relevant theme?"],
        ),
        quality_rules=_rules(["ANO", "MES", "COD_MUN_IBGE"], freshness_threshold=0.9),
        product_capabilities=["tematica_territorial", "capacidade_operacional"],
    ),
    EnterpriseDataset(
        dataset_id="tesouro_siconfi_municipio_silver",
        nome="Siconfi por municipio",
        descricao="Municipal fiscal and budget indicators from Siconfi.",
        fonte="Tesouro Nacional/Siconfi",
        url="https://siconfi.tesouro.gov.br/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="municipio",
        periodicidade="anual",
        chave_primaria=["ANO", "COD_MUN_IBGE", "CONTA"],
        chaves_estrangeiras_possiveis=["COD_MUN_IBGE", "COD_MUN_TSE"],
        cobertura_temporal=_coverage("2013", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=66,
        status_ingestao="not_started",
        estrategia_atualizacao="Annual load after fiscal publication; retain account taxonomy version.",
        observacoes_join="Municipal join only; no section-level precision without allocation model.",
        score_confiabilidade=0.8,
        tier=2,
        technical_metadata=_technical("tesouro_siconfi_municipio_silver", "silver", ["ANO", "UF"]),
        business_metadata=_business(
            "Adds fiscal context for operational feasibility and local public-service themes.",
            ["tematica_territorial", "capacidade_operacional"],
            ["Which municipalities show fiscal constraints or capacity?"],
        ),
        quality_rules=_rules(["ANO", "COD_MUN_IBGE", "CONTA"]),
        product_capabilities=["tematica_territorial", "capacidade_operacional"],
    ),
    EnterpriseDataset(
        dataset_id="ssp_sp_criminalidade_municipio_silver",
        nome="SSP-SP criminalidade por municipio",
        descricao="Public security indicators aggregated by municipality in Sao Paulo.",
        fonte="SSP-SP",
        url="https://www.ssp.sp.gov.br/estatistica",
        formato="parquet",
        camada_alvo="silver",
        granularidade="municipio",
        periodicidade="mensal",
        chave_primaria=["ANO", "MES", "COD_MUN_IBGE", "INDICADOR"],
        chaves_estrangeiras_possiveis=["COD_MUN_IBGE", "COD_MUN_TSE"],
        cobertura_temporal=_coverage("2001", "latest"),
        cobertura_geografica=_coverage("SP", "SP"),
        sensibilidade="public_open_data_aggregated",
        prioridade_produto=64,
        status_ingestao="not_started",
        estrategia_atualizacao="Monthly ingestion and dictionary mapping of crime categories.",
        observacoes_join="SP-only dataset; must be excluded from national runs unless coverage flag is SP.",
        score_confiabilidade=0.78,
        tier=2,
        technical_metadata=_technical("ssp_sp_criminalidade_municipio_silver", "silver", ["ANO", "MES"]),
        business_metadata=_business(
            "Supports security theme analysis for SP campaigns.",
            ["tematica_territorial", "competicao"],
            ["Where is public security a relevant territorial theme?"],
        ),
        quality_rules=_rules(["ANO", "MES", "COD_MUN_IBGE", "INDICADOR"], freshness_threshold=0.9),
        product_capabilities=["tematica_territorial", "competicao"],
    ),
    EnterpriseDataset(
        dataset_id="territorial_auxiliar_crosswalk_gold",
        nome="Crosswalk territorial TSE-IBGE",
        descricao="Canonical crosswalk between TSE municipality codes, IBGE municipality codes and normalized names.",
        fonte="TSE/IBGE",
        url="https://dadosabertos.tse.jus.br/",
        formato="parquet",
        camada_alvo="gold",
        granularidade="municipio",
        periodicidade="eleitoral",
        chave_primaria=["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "COD_MUN_IBGE"],
        chaves_estrangeiras_possiveis=["COD_MUN_TSE", "COD_MUN_IBGE"],
        cobertura_temporal=_coverage("2008", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="derived_aggregate",
        prioridade_produto=98,
        status_ingestao="ingested",
        estrategia_atualizacao="Rebuild when electoral or IBGE municipal codes change; persist ambiguity report.",
        observacoes_join="Exact when both codes exist; name-based fallback must record match confidence and ambiguity.",
        score_confiabilidade=0.94,
        tier=2,
        technical_metadata=_technical(
            "territorial_auxiliar_crosswalk_gold",
            "gold",
            ["ANO_ELEICAO", "SIGLA_UF"],
            lineage_downstream=["gold_fact_territorio_eleitoral", "gold_metricas_prioridade_territorial"],
        ),
        business_metadata=_business(
            "Prevents unreliable joins between electoral and socioeconomic data.",
            ["forca_eleitoral", "tematica_territorial", "capacidade_operacional", "eficiencia_gasto"],
            ["Can electoral and IBGE datasets be joined safely?"],
            doc="Core governed join asset.",
        ),
        quality_rules=_rules(["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "COD_MUN_IBGE"]),
        dependencies=[
            _dep("tse_resultados_eleitorais_secao_silver", "source", ["COD_MUN_TSE"], 1.0),
            _dep("ibge_malha_setores_censitarios_bronze", "source", ["COD_MUN_IBGE"], 1.0),
        ],
        product_capabilities=["forca_eleitoral", "tematica_territorial", "capacidade_operacional", "eficiencia_gasto"],
    ),
    EnterpriseDataset(
        dataset_id="tse_redes_sociais_candidatos_silver",
        nome="Redes sociais declaradas por candidatos",
        descricao="Public social media handles declared by candidates to electoral authorities.",
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="candidato",
        periodicidade="eleitoral",
        chave_primaria=["ANO_ELEICAO", "SQ_CANDIDATO", "URL_REDE_SOCIAL"],
        chaves_estrangeiras_possiveis=["SQ_CANDIDATO"],
        cobertura_temporal=_coverage("2018", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="public_open_data_personal",
        prioridade_produto=56,
        status_ingestao="available",
        estrategia_atualizacao="Refresh from candidate registration datasets and keep only declared public URLs.",
        observacoes_join="Exact by SQ_CANDIDATO; do not enrich with follower-level personal data.",
        score_confiabilidade=0.76,
        tier=3,
        technical_metadata=_technical("tse_redes_sociais_candidatos_silver", "silver", ["ANO_ELEICAO", "SG_UF"]),
        business_metadata=_business(
            "Complements candidate context with declared public communication channels.",
            ["contexto_candidato"],
            ["Which public channels are officially declared by the candidate?"],
        ),
        quality_rules=_rules(["ANO_ELEICAO", "SQ_CANDIDATO", "URL_REDE_SOCIAL"]),
        product_capabilities=["contexto_candidato"],
    ),
    EnterpriseDataset(
        dataset_id="meta_ad_library_campanha_silver",
        nome="Meta Ad Library por campanha",
        descricao="Public political ad metadata, spend ranges and impression ranges from Meta Ad Library.",
        fonte="Meta Ad Library",
        url="https://www.facebook.com/ads/library/api/",
        formato="json/parquet",
        camada_alvo="silver",
        granularidade="campanha",
        periodicidade="diaria",
        chave_primaria=["AD_ID", "DATE_START", "PAGE_ID"],
        chaves_estrangeiras_possiveis=["SQ_CANDIDATO", "COD_MUN_IBGE", "UF"],
        cobertura_temporal=_coverage("2019", "latest"),
        cobertura_geografica=_coverage("BR", "BR", "Political ads API coverage depends on platform availability."),
        sensibilidade="manual_review_required",
        prioridade_produto=58,
        status_ingestao="not_started",
        estrategia_atualizacao="Daily incremental API load with query audit and spend-range normalization.",
        observacoes_join="Candidate/page matching is probabilistic and requires manual review or declared-page evidence.",
        score_confiabilidade=0.62,
        tier=3,
        technical_metadata=_technical(
            "meta_ad_library_campanha_silver", "silver", ["DATE_START", "UF"], incremental_key="DATE_START"
        ),
        business_metadata=_business(
            "Adds paid media context and channel efficiency when public evidence is reliable.",
            ["eficiencia_gasto", "competicao", "contexto_candidato"],
            ["Which messages and channels are visible in paid media?", "Where is competitor spend visible?"],
            gaps=["Spend is often a range and territory attribution can be incomplete."],
        ),
        quality_rules=_rules(["AD_ID", "DATE_START", "PAGE_ID"], freshness_threshold=0.85),
        product_capabilities=["eficiencia_gasto", "competicao", "contexto_candidato"],
        lacunas=["Requires platform access and policy-compliant collection strategy."],
    ),
    EnterpriseDataset(
        dataset_id="sinais_digitais_competitivos_municipio_silver",
        nome="Sinais digitais e competitivos agregados",
        descricao="Aggregated public digital trend and competitive signals by theme and territory.",
        fonte="Public aggregated digital sources",
        url="https://trends.google.com/",
        formato="parquet",
        camada_alvo="silver",
        granularidade="municipio",
        periodicidade="semanal",
        chave_primaria=["ANO", "SEMANA", "COD_MUN_IBGE", "TEMA", "FONTE"],
        chaves_estrangeiras_possiveis=["COD_MUN_IBGE", "COD_MUN_TSE", "TEMA"],
        cobertura_temporal=_coverage("2020", "latest"),
        cobertura_geografica=_coverage("BR", "BR", "Coverage depends on source sample thresholds."),
        sensibilidade="manual_review_required",
        prioridade_produto=46,
        status_ingestao="manual_review",
        estrategia_atualizacao="Weekly load only for aggregate public signals; require source confidence scoring.",
        observacoes_join="Use as weak signal only; never infer individual preference or voter-level behavior.",
        score_confiabilidade=0.48,
        tier=3,
        technical_metadata=_technical(
            "sinais_digitais_competitivos_municipio_silver", "silver", ["ANO", "SEMANA", "UF"]
        ),
        business_metadata=_business(
            "Adds exploratory theme demand signals where public aggregate coverage is sufficient.",
            ["tematica_territorial", "competicao"],
            ["Which themes show public aggregate attention by territory?"],
            gaps=["Source sampling and API limits can bias small territories."],
        ),
        quality_rules=_rules(["ANO", "SEMANA", "COD_MUN_IBGE", "TEMA", "FONTE"], freshness_threshold=0.75),
        product_capabilities=["tematica_territorial", "competicao"],
        lacunas=["Needs governance review before commercial use."],
    ),
    EnterpriseDataset(
        dataset_id="gold_fact_territorio_eleitoral",
        nome="Fato territorio eleitoral",
        descricao="Gold fact table joining electoral, territorial, census and location signals by section/zone/municipality.",
        fonte="Derived lakehouse gold",
        url="lake://gold/gold_fact_territorio_eleitoral",
        formato="parquet",
        camada_alvo="gold",
        granularidade="secao",
        periodicidade="eleitoral",
        chave_primaria=["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO"],
        chaves_estrangeiras_possiveis=["COD_MUN_IBGE", "CD_SETOR", "SQ_CANDIDATO"],
        cobertura_temporal=_coverage("2014", "latest"),
        cobertura_geografica=_coverage("BR", "BR"),
        sensibilidade="derived_aggregate",
        prioridade_produto=99,
        status_ingestao="available",
        estrategia_atualizacao="Rebuild after any upstream TSE/IBGE source changes; persist join-confidence columns.",
        observacoes_join="Uses exact TSE joins and crosswalk-mediated IBGE joins; geospatial sector joins remain approximate.",
        score_confiabilidade=0.9,
        tier=1,
        technical_metadata=_technical(
            "gold_fact_territorio_eleitoral",
            "gold",
            ["ANO_ELEICAO", "SIGLA_UF"],
            lineage_upstream=[
                "tse_resultados_eleitorais_secao_silver",
                "tse_eleitorado_local_votacao_silver",
                "tse_perfil_eleitorado_secao_silver",
                "territorial_auxiliar_crosswalk_gold",
                "ibge_censo_2022_agregados_setor_silver",
            ],
            lineage_downstream=["gold_metricas_prioridade_territorial", "gold_recomendacao_alocacao_serving"],
        ),
        business_metadata=_business(
            "Canonical analytical table for territorial ranking, maps and score generation.",
            [
                "forca_eleitoral",
                "competicao",
                "tematica_territorial",
                "capacidade_operacional",
                "eficiencia_gasto",
            ],
            [
                "What data exists for each section?",
                "What confidence should be attached to each territorial join?",
            ],
            doc="Primary governed fact table for decision intelligence.",
        ),
        quality_rules=_rules(["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO"]),
        dependencies=[
            _dep(
                "tse_resultados_eleitorais_secao_silver",
                "gold_input",
                ["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO"],
                1.0,
            ),
            _dep("territorial_auxiliar_crosswalk_gold", "crosswalk", ["COD_MUN_TSE", "COD_MUN_IBGE"], 0.94),
            _dep("ibge_censo_2022_agregados_setor_silver", "enrichment", ["CD_SETOR"], 0.82),
        ],
        product_capabilities=[
            "forca_eleitoral",
            "competicao",
            "tematica_territorial",
            "capacidade_operacional",
            "eficiencia_gasto",
        ],
    ),
    EnterpriseDataset(
        dataset_id="gold_metricas_prioridade_territorial",
        nome="Metricas de prioridade territorial",
        descricao="Gold score table with base strength, expansion, competition, cost efficiency and operational capacity.",
        fonte="Derived scoring engine",
        url="lake://gold/gold_metricas_prioridade_territorial",
        formato="parquet",
        camada_alvo="gold",
        granularidade="zona",
        periodicidade="semanal",
        chave_primaria=["RUN_ID", "CANDIDATE_ID", "ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA"],
        chaves_estrangeiras_possiveis=["CANDIDATE_ID", "COD_MUN_TSE", "COD_MUN_IBGE", "ZONA"],
        cobertura_temporal=_coverage("current_cycle", "current_cycle"),
        cobertura_geografica=_coverage("configured_scope", "configured_scope"),
        sensibilidade="derived_aggregate",
        prioridade_produto=97,
        status_ingestao="available",
        estrategia_atualizacao="Recompute after ingestion updates or strategy-weight configuration changes.",
        observacoes_join="Consumes governed gold fact and candidate context; output must retain component-level explanations.",
        score_confiabilidade=0.86,
        tier=1,
        technical_metadata=_technical(
            "gold_metricas_prioridade_territorial",
            "gold",
            ["RUN_ID", "SIGLA_UF"],
            lineage_upstream=["gold_fact_territorio_eleitoral", "tse_prestacao_contas_candidato_silver"],
            lineage_downstream=["gold_recomendacao_alocacao_serving"],
        ),
        business_metadata=_business(
            "Turns data assets into decision-oriented territory scores.",
            [
                "forca_eleitoral",
                "competicao",
                "eficiencia_gasto",
                "tematica_territorial",
                "capacidade_operacional",
            ],
            ["Which territories deserve priority?", "Why is a territory high or low priority?"],
            doc="Business-facing scoring table.",
        ),
        quality_rules=_rules(["RUN_ID", "CANDIDATE_ID", "ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA"]),
        dependencies=[
            _dep(
                "gold_fact_territorio_eleitoral", "gold_input", ["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA"], 0.9
            ),
            _dep("tse_prestacao_contas_candidato_silver", "enrichment", ["SQ_CANDIDATO"], 0.78),
        ],
        product_capabilities=[
            "forca_eleitoral",
            "competicao",
            "eficiencia_gasto",
            "tematica_territorial",
            "capacidade_operacional",
        ],
    ),
    EnterpriseDataset(
        dataset_id="gold_recomendacao_alocacao_serving",
        nome="Recomendacao de alocacao para serving",
        descricao="Allocation recommendations with suggested action, budget share, confidence and evidence links.",
        fonte="Derived allocation engine",
        url="lake://gold/gold_recomendacao_alocacao_serving",
        formato="parquet/json",
        camada_alvo="gold",
        granularidade="zona",
        periodicidade="sob_demanda",
        chave_primaria=["SCENARIO_ID", "CANDIDATE_ID", "TERRITORIO_ID", "TIPO_ACAO"],
        chaves_estrangeiras_possiveis=["CANDIDATE_ID", "TERRITORIO_ID", "RUN_ID"],
        cobertura_temporal=_coverage("current_cycle", "current_cycle"),
        cobertura_geografica=_coverage("configured_scope", "configured_scope"),
        sensibilidade="campaign_operational_confidential",
        prioridade_produto=96,
        status_ingestao="available",
        estrategia_atualizacao="Generated per scenario; version every recommendation run with evidence manifest.",
        observacoes_join="Serving output must link back to score run and evidence records; not a raw data source.",
        score_confiabilidade=0.84,
        tier=1,
        technical_metadata=_technical(
            "gold_recomendacao_alocacao_serving",
            "gold",
            ["SCENARIO_ID"],
            lineage_upstream=["gold_metricas_prioridade_territorial", "gold_fact_territorio_eleitoral"],
        ),
        business_metadata=_business(
            "Commercial decision artifact for budget allocation and executive reporting.",
            [
                "forca_eleitoral",
                "competicao",
                "eficiencia_gasto",
                "tematica_territorial",
                "capacidade_operacional",
                "contexto_candidato",
            ],
            ["Where should campaign resources go?", "What is the evidence behind each recommendation?"],
            doc="Serving contract for API, Streamlit UI and client reports.",
        ),
        quality_rules=_rules(["SCENARIO_ID", "CANDIDATE_ID", "TERRITORIO_ID", "TIPO_ACAO"]),
        dependencies=[
            _dep("gold_metricas_prioridade_territorial", "serving_input", ["RUN_ID", "CANDIDATE_ID"], 0.86),
            _dep("gold_fact_territorio_eleitoral", "serving_input", ["TERRITORIO_ID"], 0.9),
        ],
        product_capabilities=[
            "forca_eleitoral",
            "competicao",
            "eficiencia_gasto",
            "tematica_territorial",
            "capacidade_operacional",
            "contexto_candidato",
        ],
    ),
)


def build_enterprise_catalog() -> EnterpriseDataCatalog:
    return EnterpriseDataCatalog(datasets=list(ENTERPRISE_DATASETS))


def enterprise_dataset_by_id(dataset_id: str) -> EnterpriseDataset | None:
    normalized = dataset_id.strip().lower()
    return next((dataset for dataset in ENTERPRISE_DATASETS if dataset.dataset_id.lower() == normalized), None)


def datasets_by_product_capability(capability: ProductCapability) -> list[EnterpriseDataset]:
    return [dataset for dataset in ENTERPRISE_DATASETS if capability in dataset.product_capabilities]


def datasets_by_tier(tier: int) -> list[EnterpriseDataset]:
    return [dataset for dataset in ENTERPRISE_DATASETS if dataset.tier == tier]


def catalog_gaps(catalog: EnterpriseDataCatalog | None = None) -> list[EnterpriseDataset]:
    source = catalog or build_enterprise_catalog()
    return [
        dataset
        for dataset in source.datasets
        if dataset.status_ingestao in {"not_started", "failed", "manual_review"} or dataset.lacunas
    ]


def prioritization_table(catalog: EnterpriseDataCatalog | None = None) -> list[PrioritizationRow]:
    source = catalog or build_enterprise_catalog()
    rows = [
        PrioritizationRow(
            dataset_id=dataset.dataset_id,
            tier=dataset.tier,
            prioridade_produto=dataset.prioridade_produto,
            score_confiabilidade=dataset.score_confiabilidade,
            status_ingestao=dataset.status_ingestao,
            capacidades_produto=dataset.product_capabilities,
            impacto_comercial=_impact(dataset.prioridade_produto, dataset.tier),
            lacunas_bloqueantes=dataset.lacunas + dataset.business_metadata.lacunas_conhecidas,
        )
        for dataset in source.datasets
    ]
    return sorted(rows, key=lambda row: (row.prioridade_produto, row.score_confiabilidade), reverse=True)


def coverage_summary(catalog: EnterpriseDataCatalog | None = None) -> dict[str, list[str]]:
    source = catalog or build_enterprise_catalog()
    return {
        "temporal": sorted(
            {f"{dataset.cobertura_temporal.start}:{dataset.cobertura_temporal.end}" for dataset in source.datasets}
        ),
        "geografica": sorted(
            {f"{dataset.cobertura_geografica.start}:{dataset.cobertura_geografica.end}" for dataset in source.datasets}
        ),
        "granularidade": sorted({dataset.granularidade for dataset in source.datasets}),
    }


def required_capabilities_present(
    capabilities: Iterable[ProductCapability],
    catalog: EnterpriseDataCatalog | None = None,
) -> bool:
    source = catalog or build_enterprise_catalog()
    present = {capability for dataset in source.datasets for capability in dataset.product_capabilities}
    return set(capabilities).issubset(present)


def _impact(priority: int, tier: int) -> Literal["critical", "high", "medium", "low"]:
    if tier == 1 and priority >= 90:
        return "critical"
    if priority >= 75:
        return "high"
    if priority >= 55:
        return "medium"
    return "low"
