from __future__ import annotations

from data_catalog.models import DataCatalog, DataSourceSpec

PRIORITY_SOURCES: tuple[DataSourceSpec, ...] = (
    DataSourceSpec(
        name="tse_resultados_secao_boletim_urna",
        tier=1,
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        granularidade="secao",
        periodicidade="eleitoral",
        formato="csv/zip",
        chaves_principais=["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO"],
        prioridade=100,
        status_ingestao="ingested",
        estrategia_normalizacao="Filtrar ano/turno/cargo, padronizar codigos TSE, agregar por secao/zona e preservar evidencia do cargo.",
    ),
    DataSourceSpec(
        name="tse_perfil_eleitorado_secao",
        tier=1,
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        granularidade="secao",
        periodicidade="eleitoral",
        formato="csv/zip",
        chaves_principais=["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO"],
        prioridade=98,
        status_ingestao="available",
        estrategia_normalizacao="Normalizar faixa etaria, genero e escolaridade apenas em forma agregada por secao.",
    ),
    DataSourceSpec(
        name="tse_eleitorado_local_votacao",
        tier=1,
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        granularidade="secao",
        periodicidade="eleitoral",
        formato="csv/zip",
        chaves_principais=["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "LOCAL_VOTACAO"],
        prioridade=96,
        status_ingestao="ingested",
        estrategia_normalizacao="Manter geolocalizacao do local de votacao e publicar dimensao territorial por zona/secao.",
    ),
    DataSourceSpec(
        name="tse_cadastro_candidatos",
        tier=1,
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        granularidade="candidato",
        periodicidade="eleitoral",
        formato="csv/zip",
        chaves_principais=["ANO_ELEICAO", "SQ_CANDIDATO", "SG_UF", "CD_CARGO"],
        prioridade=94,
        status_ingestao="available",
        estrategia_normalizacao="Criar CandidateProfile inicial e vincular partido, cargo, municipio de nascimento e redes declaradas.",
    ),
    DataSourceSpec(
        name="tse_prestacao_contas",
        tier=1,
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        granularidade="candidato",
        periodicidade="eleitoral",
        formato="csv/zip",
        chaves_principais=["ANO_ELEICAO", "SQ_CANDIDATO", "SG_UF"],
        prioridade=90,
        status_ingestao="available",
        estrategia_normalizacao="Agregar receita/despesa por candidato e territorio quando a despesa declarar municipio.",
    ),
    DataSourceSpec(
        name="ibge_malha_setores_censitarios",
        tier=1,
        fonte="IBGE",
        url="https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais.html",
        granularidade="setor_censitario",
        periodicidade="decenal",
        formato="shp/geopackage",
        chaves_principais=["CD_SETOR", "COD_MUN_IBGE"],
        prioridade=88,
        status_ingestao="not_started",
        estrategia_normalizacao="Persistir geometria ou centroide em camada silver e relacionar com locais de votacao por geoespacialidade.",
    ),
    DataSourceSpec(
        name="ibge_agregados_censo_2022",
        tier=1,
        fonte="IBGE",
        url="https://sidra.ibge.gov.br/",
        granularidade="setor_censitario",
        periodicidade="decenal",
        formato="api/csv",
        chaves_principais=["CD_SETOR", "COD_MUN_IBGE"],
        prioridade=86,
        status_ingestao="not_started",
        estrategia_normalizacao="Selecionar variaveis socioeconomicas agregadas e criar proxies tematicos sem microtargeting individual.",
    ),
    DataSourceSpec(
        name="inep_censo_escolar",
        tier=2,
        fonte="INEP",
        url="https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/censo-escolar",
        granularidade="municipio",
        periodicidade="anual",
        formato="csv/zip",
        chaves_principais=["COD_MUN_IBGE", "ANO"],
        prioridade=70,
        status_ingestao="not_started",
        estrategia_normalizacao="Agregar escolas, matriculas e indicadores educacionais por municipio/setor quando possivel.",
    ),
    DataSourceSpec(
        name="datasus_cnes",
        tier=2,
        fonte="DATASUS/CNES",
        url="https://datasus.saude.gov.br/transferencia-de-arquivos/",
        granularidade="municipio",
        periodicidade="mensal",
        formato="dbc/csv",
        chaves_principais=["COD_MUN_IBGE", "ANO", "MES"],
        prioridade=68,
        status_ingestao="not_started",
        estrategia_normalizacao="Agregar estabelecimentos e capacidade instalada de saude por municipio.",
    ),
    DataSourceSpec(
        name="tesouro_siconfi",
        tier=2,
        fonte="Tesouro Nacional/Siconfi",
        url="https://siconfi.tesouro.gov.br/",
        granularidade="municipio",
        periodicidade="anual",
        formato="api/csv",
        chaves_principais=["COD_MUN_IBGE", "ANO"],
        prioridade=64,
        status_ingestao="not_started",
        estrategia_normalizacao="Agregar indicadores fiscais municipais e normalizar por populacao.",
    ),
    DataSourceSpec(
        name="ssp_sp_estatisticas_criminais",
        tier=2,
        fonte="SSP-SP",
        url="https://www.ssp.sp.gov.br/estatistica",
        granularidade="municipio",
        periodicidade="mensal",
        formato="xlsx/csv",
        chaves_principais=["COD_MUN_IBGE", "ANO", "MES"],
        prioridade=60,
        status_ingestao="not_started",
        estrategia_normalizacao="Agregar ocorrencias por municipio e tema de seguranca publica.",
    ),
    DataSourceSpec(
        name="tse_redes_sociais_declaradas_candidatos",
        tier=3,
        fonte="TSE",
        url="https://dadosabertos.tse.jus.br/",
        granularidade="candidato",
        periodicidade="eleitoral",
        formato="csv/zip",
        chaves_principais=["ANO_ELEICAO", "SQ_CANDIDATO", "URL_REDE_SOCIAL"],
        prioridade=54,
        status_ingestao="available",
        estrategia_normalizacao="Vincular apenas perfis declarados/publicos ao CandidateProfile; nao inferir atributos individuais de seguidores.",
    ),
    DataSourceSpec(
        name="meta_ad_library",
        tier=3,
        fonte="Meta Ad Library",
        url="https://www.facebook.com/ads/library/api/",
        granularidade="campanha",
        periodicidade="diaria",
        formato="api/json",
        chaves_principais=["candidate_id", "ad_id", "date_start"],
        prioridade=50,
        status_ingestao="not_started",
        estrategia_normalizacao="Manter somente dados publicos/agregados de anuncios; nao inferir preferencia individual.",
    ),
    DataSourceSpec(
        name="sinais_digitais_auxiliares_agregados",
        tier=3,
        fonte="Fontes publicas agregadas",
        url="https://trends.google.com/",
        granularidade="municipio",
        periodicidade="semanal",
        formato="api/csv",
        chaves_principais=["ANO", "SEMANA", "COD_MUN_IBGE", "TEMA"],
        prioridade=42,
        status_ingestao="manual_review",
        estrategia_normalizacao="Usar apenas sinais agregados por tema/territorio, com revisao humana e sem perfilamento individual.",
    ),
)


def build_default_catalog() -> DataCatalog:
    return DataCatalog(sources=list(PRIORITY_SOURCES))


def source_by_name(name: str) -> DataSourceSpec | None:
    normalized = name.strip().lower()
    return next((source for source in PRIORITY_SOURCES if source.name.lower() == normalized), None)
