from __future__ import annotations

from feature_store.models import FeatureFamily, FeatureSpec

FEATURE_REGISTRY: tuple[FeatureSpec, ...] = (
    FeatureSpec(
        feature_name="historical_vote_share",
        family="base_eleitoral",
        definition="Candidate vote share inside the territory using aggregated nominal votes.",
        grain="candidate_id + territorio_id",
        dtype="float",
        lineage=["gold_electoral_base_strength"],
        recomputation_policy="after electoral results refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="territorial_concentration",
        family="base_eleitoral",
        definition="Share of candidate total observed votes concentrated in the territory.",
        grain="candidate_id + territorio_id",
        dtype="float",
        lineage=["gold_electoral_base_strength"],
        recomputation_policy="after electoral results refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="electoral_volatility",
        family="base_eleitoral",
        definition="Standard deviation of candidate vote share across observed election years for the same territory.",
        grain="candidate_id + territorio_id",
        dtype="float",
        lineage=["gold_electoral_base_strength"],
        recomputation_policy="after historical backfill or election refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="retention_score",
        family="base_eleitoral",
        definition="Proxy of retention potential using base strength and historical vote share.",
        grain="candidate_id + territorio_id",
        dtype="float",
        lineage=["gold_electoral_base_strength"],
        recomputation_policy="after score component refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="stronghold_presence",
        family="base_eleitoral",
        definition="Boolean indicator that the territory behaves as a candidate stronghold.",
        grain="candidate_id + territorio_id",
        dtype="bool",
        lineage=["gold_electoral_base_strength"],
        recomputation_policy="after base strength refresh",
    ),
    FeatureSpec(
        feature_name="relevant_competitor_count",
        family="competicao",
        definition="Number of candidates with relevant base strength in the territory.",
        grain="territorio_id",
        dtype="int",
        lineage=["gold_electoral_base_strength"],
        recomputation_policy="after base strength refresh",
    ),
    FeatureSpec(
        feature_name="vote_fragmentation",
        family="competicao",
        definition="One minus Herfindahl concentration of candidate vote shares in the territory.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_electoral_base_strength"],
        recomputation_policy="after electoral results refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="competitive_intensity",
        family="competicao",
        definition="Territorial competition score inherited from the competition landscape mart.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_competition_landscape"],
        recomputation_policy="after competition mart refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="competitor_incumbency_pressure",
        family="competicao",
        definition="Share of relevant competitors flagged as incumbents when candidate context provides incumbency.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_candidate_context", "gold_electoral_base_strength"],
        recomputation_policy="after candidate context refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="population_density_proxy",
        family="territorial",
        definition="Normalized territorial density proxy from census or territory profile fields.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_territory_profile", "silver_ibge_agregados_censo"],
        recomputation_policy="after territorial profile refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="urbanization_proxy",
        family="territorial",
        definition="Urbanization proxy derived from density, section count and polling-place availability.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_territory_profile"],
        recomputation_policy="after territorial profile refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="institutional_presence",
        family="territorial",
        definition="Normalized proxy of institutional presence using voting places or public facilities.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_territory_profile", "thematic public services sources"],
        recomputation_policy="after territorial or thematic source refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="social_indicator_score",
        family="territorial",
        definition="Aggregated socioeconomic signal for territorial context.",
        grain="territorio_id",
        dtype="float",
        lineage=["silver_ibge_agregados_censo", "gold_territory_profile"],
        recomputation_policy="after census/territorial refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="candidate_territory_thematic_affinity",
        family="tematica",
        definition="Affinity between candidate themes and territorial thematic signals.",
        grain="candidate_id + territorio_id",
        dtype="float",
        lineage=["gold_thematic_affinity", "gold_candidate_context"],
        recomputation_policy="after thematic or candidate context refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="thematic_coherence",
        family="tematica",
        definition="Consistency of thematic affinity across themes for a territory.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_thematic_affinity"],
        recomputation_policy="after thematic mart refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="theme_competitive_saturation",
        family="tematica",
        definition="Proxy for competitive saturation around themes in a territory.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_thematic_affinity", "gold_competition_landscape"],
        recomputation_policy="after thematic or competition refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="estimated_cost_per_vote",
        family="eficiencia",
        definition="Estimated spend divided by observed votes for the candidate.",
        grain="candidate_id",
        dtype="float",
        lineage=["gold_campaign_finance_efficiency"],
        recomputation_policy="after campaign finance refresh",
        quality_rules=["non-negative"],
    ),
    FeatureSpec(
        feature_name="spend_result_elasticity",
        family="eficiencia",
        definition="Normalized votes per unit of campaign spend as a rough elasticity proxy.",
        grain="candidate_id",
        dtype="float",
        lineage=["gold_campaign_finance_efficiency"],
        recomputation_policy="after finance or result refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="local_financial_intensity",
        family="eficiencia",
        definition="Relative campaign financial intensity for the candidate.",
        grain="candidate_id",
        dtype="float",
        lineage=["gold_campaign_finance_efficiency"],
        recomputation_policy="after campaign finance refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="base_proximity",
        family="operacional",
        definition="Operational proximity to existing base, using base strength as a proxy.",
        grain="candidate_id + territorio_id",
        dtype="float",
        lineage=["gold_electoral_base_strength"],
        recomputation_policy="after base strength refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="logistical_complexity",
        family="operacional",
        definition="Operational difficulty proxy using section count and data quality limitations.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_territory_profile"],
        recomputation_policy="after territorial profile refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="territory_size",
        family="operacional",
        definition="Normalized size proxy using section count.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_territory_profile"],
        recomputation_policy="after territorial profile refresh",
        quality_rules=["value between 0 and 1"],
    ),
    FeatureSpec(
        feature_name="polling_place_centrality",
        family="operacional",
        definition="Proxy for operational centrality using voting-place concentration.",
        grain="territorio_id",
        dtype="float",
        lineage=["gold_territory_profile"],
        recomputation_policy="after voting-place refresh",
        quality_rules=["value between 0 and 1"],
    ),
)


def all_features() -> list[FeatureSpec]:
    return list(FEATURE_REGISTRY)


def feature_by_name(feature_name: str) -> FeatureSpec | None:
    normalized = feature_name.strip().lower()
    return next((feature for feature in FEATURE_REGISTRY if feature.feature_name.lower() == normalized), None)


def features_by_family(family: FeatureFamily) -> list[FeatureSpec]:
    return [feature for feature in FEATURE_REGISTRY if feature.family == family]


def registry_lineage() -> list[str]:
    return sorted({source for feature in FEATURE_REGISTRY for source in feature.lineage})
