from __future__ import annotations

from lakehouse.contracts import DatasetContract, LakehouseCatalog, PartitionPolicy


def build_electoral_lakehouse_catalog() -> LakehouseCatalog:
    datasets = [
        DatasetContract(
            dataset_id="raw_tse_resultados_secao_boletim_urna",
            layer="bronze",
            owner="data_platform",
            entity="electoral_result",
            fact_or_dimension="source_snapshot",
            business_description="Arquivo bruto oficial do TSE preservado como evidencia de votos por secao/boletim de urna.",
            source_name="tse_resultados_secao_boletim_urna",
            source_url="https://dadosabertos.tse.jus.br/",
            granularity="ano_eleicao + uf + municipio_tse + zona + secao + cargo + candidato",
            primary_key=["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO"],
            schema={
                "ANO_ELEICAO": "int64",
                "SIGLA_UF": "string",
                "COD_MUN_TSE": "string",
                "ZONA": "int64",
                "SECAO": "int64",
            },
            required_columns=["ANO_ELEICAO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO"],
            partition_policy=PartitionPolicy(
                columns=["ANO_ELEICAO", "SIGLA_UF"],
                description="Particionar por ano eleitoral e UF para reprocessamento incremental por eleicao/estado.",
            ),
            incremental_strategy="append",
            coverage={"territorio": "Brasil", "periodicidade": "eleitoral"},
            quality_rules=[
                "hash do arquivo original obrigatorio",
                "schema minimo TSE detectado",
                "sem transformacao destrutiva",
            ],
            lgpd_classification="public_open_data_aggregated",
            business_documentation="Fonte primaria para base eleitoral, abstencao, ranking de secao e volatilidade historica.",
        ),
        DatasetContract(
            dataset_id="silver_tse_resultados_secao",
            layer="silver",
            owner="data_platform",
            entity="electoral_result",
            fact_or_dimension="fact",
            business_description="Resultado eleitoral limpo, tipado, deduplicado e harmonizado nas chaves territoriais canonicas.",
            source_name="tse_resultados_secao_boletim_urna",
            source_url="https://dadosabertos.tse.jus.br/",
            granularity="ano_eleicao + turno + uf + municipio_tse + zona + secao + candidato",
            primary_key=["ANO_ELEICAO", "TURNO", "SIGLA_UF", "COD_MUN_TSE", "ZONA", "SECAO", "ID_CANDIDATO"],
            schema={
                "ANO_ELEICAO": "int64",
                "TURNO": "int64",
                "SIGLA_UF": "string",
                "COD_MUN_TSE": "string",
                "COD_MUN_IBGE": "string",
                "MUNICIPIO": "string",
                "ZONA": "int64",
                "SECAO": "int64",
                "ID_CANDIDATO": "string",
                "VOTOS_NOMINAIS": "int64",
                "join_confidence": "float64",
                "data_quality_score": "float64",
                "source_hash_sha256": "string",
                "ingested_at_utc": "string",
            },
            required_columns=[
                "ANO_ELEICAO",
                "TURNO",
                "SIGLA_UF",
                "COD_MUN_TSE",
                "ZONA",
                "SECAO",
                "ID_CANDIDATO",
                "VOTOS_NOMINAIS",
                "join_confidence",
                "data_quality_score",
            ],
            partition_policy=PartitionPolicy(
                columns=["ANO_ELEICAO", "SIGLA_UF"], description="Carga incremental por eleicao/UF."
            ),
            incremental_strategy="upsert_by_key",
            lineage_inputs=["raw_tse_resultados_secao_boletim_urna"],
            coverage={"territorio": "Brasil", "nivel": "secao"},
            quality_rules=["primary_key unica", "join_confidence entre 0 e 1", "data_quality_score entre 0 e 1"],
            business_documentation="Base silver para granularidade maxima de secao, preservando origem e qualidade de join.",
        ),
        DatasetContract(
            dataset_id="gold_fact_territorio_eleitoral",
            layer="gold",
            owner="analytics_engineering",
            entity="territory",
            fact_or_dimension="fact",
            business_description="Tabela analitica consolidada por territorio eleitoral para scoring, recomendacao e dashboards.",
            source_name="lakehouse_consolidation",
            granularity="ano_eleicao + uf + municipio_tse + zona + secao/local_votacao/setor quando disponivel",
            primary_key=["territorio_id"],
            schema={
                "territorio_id": "string",
                "ANO_ELEICAO": "int64",
                "SIGLA_UF": "string",
                "COD_MUN_TSE": "string",
                "COD_MUN_IBGE": "string",
                "MUNICIPIO": "string",
                "ZONA": "int64",
                "SECAO": "int64",
                "LOCAL_VOTACAO": "string",
                "CD_SETOR": "string",
                "eleitores_aptos": "int64",
                "votos_validos": "int64",
                "abstencao_pct": "float64",
                "competitividade": "float64",
                "join_confidence": "float64",
                "data_quality_score": "float64",
            },
            required_columns=[
                "territorio_id",
                "ANO_ELEICAO",
                "SIGLA_UF",
                "COD_MUN_TSE",
                "MUNICIPIO",
                "join_confidence",
                "data_quality_score",
            ],
            partition_policy=PartitionPolicy(
                columns=["ANO_ELEICAO", "SIGLA_UF"], description="Reprocessamento por ciclo eleitoral e UF."
            ),
            incremental_strategy="merge_by_partition",
            lineage_inputs=[
                "silver_tse_resultados_secao",
                "silver_tse_eleitorado_local_votacao",
                "silver_ibge_setores",
            ],
            coverage={"territorio": "SP prioritario; Brasil extensivel", "nivel": "secao/zona/local/setor"},
            quality_rules=[
                "territorio_id unico",
                "documentar joins exatos e aproximados",
                "coverage territorial calculada",
            ],
            business_documentation="Camada de consumo para motores de score, contexto de candidato e priorizacao territorial.",
        ),
        DatasetContract(
            dataset_id="semantic_metricas_prioridade_territorial",
            layer="semantic",
            owner="analytics_product",
            entity="score",
            fact_or_dimension="metric_view",
            business_description="Visao canonica de metricas e scores usados pelo produto para decisao de alocacao.",
            source_name="scoring_engine",
            granularity="territorio_id + candidate_id + scenario + score_version",
            primary_key=["territorio_id", "candidate_id", "scenario", "score_version"],
            schema={
                "territorio_id": "string",
                "candidate_id": "string",
                "scenario": "string",
                "score_version": "string",
                "base_eleitoral_score": "float64",
                "afinidade_tematica_score": "float64",
                "potencial_expansao_score": "float64",
                "custo_eficiencia_score": "float64",
                "concorrencia_score": "float64",
                "score_prioridade_final": "float64",
                "confidence_score": "float64",
            },
            required_columns=[
                "territorio_id",
                "candidate_id",
                "scenario",
                "score_version",
                "score_prioridade_final",
                "confidence_score",
            ],
            partition_policy=PartitionPolicy(
                columns=["scenario", "score_version"], description="Versionar metricas por estrategia e pesos."
            ),
            incremental_strategy="upsert_by_key",
            lineage_inputs=["gold_fact_territorio_eleitoral", "candidate_context"],
            coverage={"produto": "ranking, simulacao, explicabilidade"},
            quality_rules=["scores entre 0 e 1", "confidence_score entre 0 e 1", "score_version obrigatoria"],
            lgpd_classification="derived_aggregate",
            business_documentation="Contrato semantico para API/UI: nomes estaveis de metricas e definicoes de negocio.",
        ),
        DatasetContract(
            dataset_id="serving_recomendacao_alocacao",
            layer="serving",
            owner="product_engineering",
            entity="allocation_recommendation",
            fact_or_dimension="serving_output",
            business_description="Output pronto para API, UI e recommendation engine com verba sugerida e justificativa auditavel.",
            source_name="allocation_engine",
            granularity="candidate_id + territorio_id + scenario + generated_at_utc",
            primary_key=["candidate_id", "territorio_id", "scenario", "generated_at_utc"],
            schema={
                "candidate_id": "string",
                "territorio_id": "string",
                "scenario": "string",
                "generated_at_utc": "string",
                "tipo_recomendacao": "string",
                "score_prioridade": "float64",
                "recurso_sugerido": "float64",
                "percentual_orcamento_sugerido": "float64",
                "justificativa": "string",
                "confidence_score": "float64",
                "evidence_ids": "string",
            },
            required_columns=[
                "candidate_id",
                "territorio_id",
                "scenario",
                "generated_at_utc",
                "score_prioridade",
                "recurso_sugerido",
                "confidence_score",
            ],
            partition_policy=PartitionPolicy(
                columns=["scenario"], description="Servir cenarios conservador/hibrido/agressivo separadamente."
            ),
            incremental_strategy="append",
            lineage_inputs=["semantic_metricas_prioridade_territorial"],
            coverage={"produto": "API/UI/recommendation"},
            quality_rules=["evidencias obrigatorias", "sem dados pessoais de eleitores", "justificativa nao vazia"],
            lgpd_classification="campaign_operational_confidential",
            business_documentation="Tabela final vendavel: ranking, verba, canal/mensagem e explicacao para cliente.",
        ),
        DatasetContract(
            dataset_id="serving_territory_ranking",
            layer="serving",
            owner="product_engineering",
            entity="territory",
            fact_or_dimension="serving_output",
            business_description="Ranking territorial final para API/UI, com score, confianca e explicacao agregada.",
            source_name="serving_layer_builder",
            granularity="tenant_id + campaign_id + snapshot_id + candidate_id + territorio_id",
            primary_key=["tenant_id", "campaign_id", "snapshot_id", "candidate_id", "territorio_id"],
            schema={
                "tenant_id": "string",
                "campaign_id": "string",
                "snapshot_id": "string",
                "dataset_version": "string",
                "generated_at_utc": "string",
                "rank": "int64",
                "candidate_id": "string",
                "territorio_id": "string",
                "uf": "string",
                "municipio_nome": "string",
                "zona": "string",
                "score_prioridade_final": "float64",
                "confidence_score": "float64",
                "join_confidence": "float64",
                "data_quality_score": "float64",
            },
            required_columns=[
                "tenant_id",
                "campaign_id",
                "snapshot_id",
                "candidate_id",
                "territorio_id",
                "score_prioridade_final",
                "confidence_score",
            ],
            partition_policy=PartitionPolicy(
                columns=["campaign_id", "snapshot_id"], description="Servir ranking por campanha e snapshot auditavel."
            ),
            incremental_strategy="append",
            lineage_inputs=["gold_priority_score", "gold_territory_profile"],
            coverage={"produto": "ranking territorial, mapa, demo comercial"},
            quality_rules=["score entre 0 e 1", "confidence_score entre 0 e 1", "sem dados individuais de eleitores"],
            lgpd_classification="derived_aggregate",
            business_documentation="Contrato canônico para endpoint /v1/serving/territory-ranking e telas de ranking.",
        ),
        DatasetContract(
            dataset_id="serving_allocation_recommendations",
            layer="serving",
            owner="product_engineering",
            entity="allocation_recommendation",
            fact_or_dimension="serving_output",
            business_description="Recomendacoes finais de alocacao por cenario, candidato e territorio.",
            source_name="serving_layer_builder",
            granularity="tenant_id + campaign_id + snapshot_id + scenario_id + candidate_id + territorio_id",
            primary_key=["tenant_id", "campaign_id", "snapshot_id", "scenario_id", "candidate_id", "territorio_id"],
            schema={
                "tenant_id": "string",
                "campaign_id": "string",
                "snapshot_id": "string",
                "dataset_version": "string",
                "generated_at_utc": "string",
                "scenario_id": "string",
                "candidate_id": "string",
                "territorio_id": "string",
                "tipo_acao_sugerida": "string",
                "score_prioridade_final": "float64",
                "recurso_sugerido": "float64",
                "percentual_orcamento_sugerido": "float64",
                "justificativa": "string",
                "confidence_score": "float64",
                "evidence_ids": "string",
            },
            required_columns=[
                "tenant_id",
                "campaign_id",
                "snapshot_id",
                "scenario_id",
                "candidate_id",
                "territorio_id",
                "recurso_sugerido",
                "confidence_score",
            ],
            partition_policy=PartitionPolicy(
                columns=["campaign_id", "snapshot_id"], description="Congelar recomendacoes por campanha/snapshot."
            ),
            incremental_strategy="append",
            lineage_inputs=["gold_allocation_recommendations", "gold_priority_score"],
            coverage={"produto": "API/UI/reports/recommendation engine"},
            quality_rules=["recurso nao negativo", "justificativa nao vazia", "evidence_ids obrigatorio"],
            lgpd_classification="campaign_operational_confidential",
            business_documentation="Contrato para recomendacoes consumidas por UI, API e relatorios premium.",
        ),
        DatasetContract(
            dataset_id="serving_data_readiness",
            layer="serving",
            owner="data_platform",
            entity="lake_health",
            fact_or_dimension="serving_output",
            business_description="Resumo de prontidao comercial e qualidade do lake para uma campanha/snapshot.",
            source_name="serving_layer_builder",
            granularity="tenant_id + campaign_id + snapshot_id",
            primary_key=["tenant_id", "campaign_id", "snapshot_id"],
            schema={
                "tenant_id": "string",
                "campaign_id": "string",
                "snapshot_id": "string",
                "dataset_version": "string",
                "generated_at_utc": "string",
                "readiness_score": "float64",
                "territories_ranked": "int64",
                "candidates_supported": "int64",
                "recommendations_available": "bool",
                "avg_join_confidence": "float64",
                "lake_health_score": "float64",
                "join_limitations": "string",
            },
            required_columns=[
                "tenant_id",
                "campaign_id",
                "snapshot_id",
                "readiness_score",
                "avg_join_confidence",
                "join_limitations",
            ],
            partition_policy=PartitionPolicy(
                columns=["campaign_id", "snapshot_id"], description="Readiness por entrega comercial auditavel."
            ),
            incremental_strategy="append",
            lineage_inputs=["lake_health_report", "gold_territorial_electoral_master_index"],
            coverage={"produto": "monitoramento, pitch, readiness comercial"},
            quality_rules=["readiness_score entre 0 e 1", "limitacoes de join sempre preenchidas"],
            lgpd_classification="derived_aggregate",
            business_documentation="Contrato para endpoint /v1/serving/data-readiness e painel de saude do produto.",
        ),
    ]
    return LakehouseCatalog(datasets=datasets)
